name: All Browsers - End-to-end tests
on: push
permissions: write-all

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
      - name: Upload chrome
        uses: actions/upload-artifact@v3
        if: always()
        continue-on-error: true
        with:
          name: chrome-run
          path: cypress/screenshots
          if-no-files-found: ignore
          retention-days: 1
  cypress-run-firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --browser firefox --config video=false
  cypress-run-edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: edge
      - name: Upload edge
        uses: actions/upload-artifact@v3
        if: always()
        continue-on-error: true
        with:
          name: video-edge-run
          path: cypress/screenshots
          if-no-files-found: ignore
