name: All Browsers - End-to-end tests
on:
  push:
  workflow_dispatch:
jobs:
  cypress-run-electron:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  cypress-run-firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --record --browser firefox
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  cypress-run-edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          record: true
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  cypress-run-safari:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install webkit dependencies for Linux
        run: npx playwright install-deps webkit
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --record --browser webkit
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`