name: All Browsers - End-to-end tests
on:
  push:
  workflow_dispatch:
jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  cypress-run-firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  cypress-run-edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: edge
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: always()
        continue-on-error: true
        with:
          name: cypress-screenshots-edge
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
